Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [2]:
import numpy as np
a=np.array([3,3,4,7])
print(a+5)
print(a*5)
print(a/3)

[ 8  8  9 12]
[15 15 20 35]
[1.         1.         1.33333333 2.33333333]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [6]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
max_count = counts.max()
mode_values = values[counts == max_count]

# Most frequent value and their indices
mode_x = mode_values[0]
indices_x = np.where(x == mode_x)[0]
print("Most frequent values =", mode_x)
print("Their values =", indices_x)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
max_count = counts.max()
mode_values = values[counts == max_count]

# Most frequent values and their indices
modes_indices_y = [(val, np.where(y == val)[0]) for val in mode_values]
print(modes_indices_y)
print(mode_values)

[5 4 6 3 2 1]
1
[0 5 7 8 9]
[(1, array([0, 1, 2])), (3, array([4, 8, 9]))]
[1 3]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [7]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# a) Access 1st row, 2nd column
element_1 = arr[0, 1]  # Accessing element at row index 0 and column index 1
print(f"Element at 1st row, 2nd column: {element_1}")

# b) Access 3rd row, 1st column
element_2 = arr[2, 0]  # Accessing element at row index 2 and column index 0
print(f"Element at 3rd row, 1st column: {element_2}")

Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [9]:
import numpy as np
keshav = np.linspace(10, 100, 25)
print("Array: ",keshav)
print("Dimensions: ",keshav.ndim)
print("Shape: ",keshav.shape)
print("Total elements: ",keshav.size)
print("Data type of each element: ",keshav.dtype)
print("Bytes consumed by the array: ",keshav.nbytes)

transpose_array=keshav.reshape(25,1)
print("Transpose of the array using reshape\n: ",transpose_array)
print("Using T attribute: ",keshav.T)
print("Shape after .T: ",keshav.T.shape)

Array:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions:  1
Shape:  (25,)
Total elements:  25
Data type of each element:  float64
Bytes consumed by the array:  200
Transpose of the array using reshape
:  [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T attribute:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape after .T:  (25,)


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [10]:
import numpy as np

ucs420_keshav = np.array([[10, 20, 30, 40],
                          [50, 60, 70, 80],
                          [90, 15, 20, 35]])

mean_value = np.mean(ucs420_keshav)
median_value = np.median(ucs420_keshav)
max_value = np.max(ucs420_keshav)
min_value = np.min(ucs420_keshav)
unique_elements = np.unique(ucs420_keshav)

print("Original 2D Array:\n", ucs420_keshav)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Max Value:", max_value)
print("Min Value:", min_value)
print("Unique Elements:", unique_elements)

reshaped_ucs420_keshav = ucs420_keshav.reshape(4, 3)
print("\nReshaped (4x3) Array:\n", reshaped_ucs420_keshav)

resized_ucs420_keshav = np.resize(ucs420_keshav, (2, 3))
print("\nResized (2x3) Array:\n", resized_ucs420_keshav)


Original 2D Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max Value: 90
Min Value: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped (4x3) Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized (2x3) Array:
 [[10 20 30]
 [40 50 60]]
